# Site Settings
baseurl: 

# Features Setting
# Turn subpages on or off
publications: True
presentations: False
blog: False
people: True
projects: True
multibody: True
halo: True

# Language of the website
lang: en

# Search engine optimization settings
title: Perception and Intelligence Laboratory (PINlab)
tagline: Department of Computer Science, Sapienza University of Rome, Italy

description: The PINlab focuses on fundamental research in computer vision and machine learning, with a focus on distributed and multi-agent systems, perception, and general intelligence. Our research is conducted within sustainable and interpretable frameworks.
author: PINlab
twitter:
  username: SapienzaPINlab
  card: Perception and Intelligence Laboratory (PINlab)
logo: assets/img/Concluded_logo_y_padded_squared_Lesspadded.png
social:
  name: PINlab
  links:
    - https://twitter.com/SapienzaPINlab
    - https://github.com/PINlabSapienza
locale: en_GB

# Page Settings
theme_settings:
  title: Grape Academic Theme

  experience_title: EXPERIENCE
  interests_title: RESEARCH INTERESTS
  skills_title: SKILLS
  awards_title: AWARDS
  projects_title: PROJECTS
  recentpubs_title: RECENT PUBLICATIONS
  presentation_text: "Computer vision and machine learning have great potential to endow machines/robots with the (visual) perception of the environment and the intelligence to reason about it, and take decisions. The field has thrived in the past three decades, and it stands now as one of the key technological ingredients for autonomous driving, unmanned drones, and human-robot-collaboration, as well as the pervasive novel asset for other fields of science, including earthquake and weather forecasting."
  presentation_text2: "Our lab is interested in fundamental research and innovation transfer on computer vision and machine learning. Our specific research interests include distributed and multi-agent intelligent systems, perception (detection, recognition, re-identification, forecasting), and general intelligence (reasoning, meta-learning, domain adaptation), within sustainable (low-power-consumption and constrained-computational-resource sensors and devices) and interpretable (interpretable and verifiable AI) frameworks."


# Pagination
# paginate: 5
# paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
plugins: ['jekyll-paginate', 'jekyll/scholar', 'jekyll-seo-tag']
bootstrap:
  assets: true

# Bibliography settings
scholar:
  bibliography: publications.bib
  bibliography_template: pubstemplate
  style: apa
  locale: en
  last_name: Me
  first_name: [Myself, M.]
  sort_by: year,month
  order: descending,ascending

filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website] # Filter out certain bibtex entry keywords used internally from the bib output

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
